/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class yifeiyuan_practice_practicedemos_jni_HelloJni */

#ifndef _Included_yifeiyuan_practice_practicedemos_jni_HelloJni
#define _Included_yifeiyuan_practice_practicedemos_jni_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     yifeiyuan_practice_practicedemos_jni_HelloJni
 * Method:    helloJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_yifeiyuan_practice_practicedemos_jni_HelloJni_helloJni
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
